### ISSUE TITLE
Add 2-trans,6-trans-farnesyl diphosphate(3-) (CHEBI:175763) to 662af8fa00000499

### ISSUE THREAD

**Issue by kimrutherford** [pombase/pombase-gocam-curation#14]
Hi Val.

Thanks for removing `dlp1` and `dps1` from the `isoprenoid biosynthetic process (GO:0008299)` model.

Could you include the `2-trans,6-trans-farnesyl diphosphate(3-) (CHEBI:175763)` output of the unknown transporter in the Noctua model?  It will help the models join up.

http://noctua.geneontology.org/workbench/noctua-visual-pathway-editor/?model_id=gomodel%3A662af8fa00000499

https://www.pombase.org/pombase_gocam_view/gene/662af8fa00000499/SPBPJ4664.01/dps1

Thanks.

**Comment by ValWood** [comment]
done

**Comment by kimrutherford** [comment]
Thanks!

**Comment by kimrutherford** [comment]
> Could you include the 2-trans,6-trans-farnesyl diphosphate(3-) (CHEBI:175763) output of the unknown transporter

This change hasn't come through even though all of your other changes have. 

https://www.pombase.org/pombase_gocam_view/docs/662af8fa00000499

Could you try saving again in Noctua?

Thanks.

**Comment by ValWood** [comment]
Weird, it's definitely there and it has the green tick. I saved again....

**Comment by PCarme** [comment]
There are definitely some weird stuff with the changes that came through or not. 
Yesterday I have fixed the 3 heterochromatin assembly models so that they should no longer join, but only the changes I have made to the pericentric heterochromatin formation pathway are on PomBase, the silent mating type cassette and subtelomeric heterochromatin models are still the same as before. 
Even more weird, even within the peri centric heterochromatin model, not all the changes went through: compare the view on [PomBase](https://www.pombase.org/gocam/term/665912ed00000652/GO:0031508/pericentric%20heterochromatin%20formation) with the [Noctua](http://noctua.geneontology.org/workbench/noctua-alliance-pathway-preview/?model_id=gomodel:665912ed00000652) one

**Comment by kimrutherford** [comment]
Yes, it's very strange.  If the changes haven't come through by Monday I'll contact the Noctua developers.

**Comment by PCarme** [comment]
> There are definitely some weird stuff with the changes that came through or not. Yesterday I have fixed the 3 heterochromatin assembly models so that they should no longer join, but only the changes I have made to the pericentric heterochromatin formation pathway are on PomBase, the silent mating type cassette and subtelomeric heterochromatin models are still the same as before. Even more weird, even within the peri centric heterochromatin model, not all the changes went through: compare the view on [PomBase](https://www.pombase.org/gocam/term/665912ed00000652/GO:0031508/pericentric%20heterochromatin%20formation) with the [Noctua](http://noctua.geneontology.org/workbench/noctua-alliance-pathway-preview/?model_id=gomodel:665912ed00000652) one

That's fixed now, and these 3 pathways no longer appear in the joined model

**Comment by kimrutherford** [comment]
The locations of `2-trans,6-trans-farnesyl diphosphate(3-) (CHEBI:175763)` are different in these two models:

https://www.pombase.org/pombase_gocam_view/docs/662af8fa00000408
`located in: mitochondrial inner membrane (GO:0005743)`

https://www.pombase.org/pombase_gocam_view/docs/662af8fa00000499
`located in: mitochondrial matrix (GO:0005759)`

Here's how they join:
https://desktop.kmr.nz/pombase_gocam_view/docs/662af8fa00000408%2B662af8fa00000499

**Comment by kimrutherford** [comment]
> That's fixed now, and these 3 pathways no longer appear in the joined model

Thanks for checking.

**Comment by kimrutherford** [comment]
> The locations of 2-trans,6-trans-farnesyl diphosphate(3-) (CHEBI:175763) are different in these two models:

Looks like that's fixed now:

![Image](https://github.com/user-attachments/assets/5e89f993-4fc9-45cd-9d05-38f00517c877)
